### PR TITLE
2023 Info Challenge Eventbot changes

### PR DESCRIPTION
**Pull request by gregjan**
This code is adjusted in several key ways..

* tweaks to permissions to match latest Discord API
* runs in a Docker Swarm now, so the database is deployed with the bot.
* also deploys "Adminer" which helps with importing database table data  from CSV.
* Several other misc changes..

### CODE REVIEW

**Comment by gregjan** [comment]
A note that Docker Hub is ending image hosting for free team accounts, a service that I used to deploy the images this year. It is quite easy to build these images on the server itself though. So that's something I'll add to the README / INSTALL docs. I'd guess that the MariaDB and Adminer images will remain available via Docker Hub.

**Comment by gregjan** [comment]
Okay nevermind, the steps to build first are already in the docs and they work.

**Comment by donalus** [comment]
This looks great and I imagine it is battle tested since the Info Challenge just happened.

**Comment by gregjan** [comment]
It is indeed. Things worked out splendid!
Greg

**Pull request merged**
